# Generated by Django 3.0.4 on 2020-03-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('get_text', models.BooleanField(default=True, verbose_name='get_text')),
                ('get_image', models.BooleanField(default=True, verbose_name='get_image')),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('failure', 'FAILURE'), ('done', 'DONE')], default='pending', max_length=20, verbose_name='state')),
            ],
            options={
                'verbose_name': 'queue task',
                'verbose_name_plural': 'queue tasks',
                'db_table': 'queue_tasks',
            },
        ),
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('text', models.TextField(null=True, verbose_name='text')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_content_extractor.QueueTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='image')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_content_extractor.QueueTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
