# Generated by Django 3.0.4 on 2020-03-21 15:18

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='get_image',
            field=models.BooleanField(default=True, verbose_name='get images'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='get_text',
            field=models.BooleanField(default=True, verbose_name='get texts'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='url',
            field=models.URLField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Invalid URL', regex='(https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})')], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='texts'),
        ),
    ]
