# Generated by Django 3.0.4 on 2020-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content_extractor', '0003_auto_20200322_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteimage',
            options={'verbose_name': 'website image', 'verbose_name_plural': 'website images'},
        ),
        migrations.AlterModelOptions(
            name='websitetext',
            options={'verbose_name': 'website text', 'verbose_name_plural': 'website texts'},
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterModelTable(
            name='websiteimage',
            table='website image',
        ),
        migrations.AlterModelTable(
            name='websitetext',
            table='website text',
        ),
    ]
