# Generated by Django 3.0.4 on 2020-03-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_content_extractor', '0004_auto_20200322_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website_content_extractor.QueueTask'),
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='website_content_extractor.QueueTask'),
        ),
    ]
