# Generated by Django 3.0.7 on 2020-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content_extractor', '0005_auto_20200322_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='get_image',
            field=models.BooleanField(blank=True, default=True, verbose_name='get images'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='get_text',
            field=models.BooleanField(blank=True, default=True, verbose_name='get texts'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('failure', 'FAILURE'), ('success', 'SUCCESS')], default='pending', max_length=20, verbose_name='state'),
        ),
    ]
