# Generated by Django 3.0.7 on 2020-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content_extractor', '0006_auto_20200606_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='get_image',
            field=models.BooleanField(blank=True, default=False, verbose_name='get images'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='get_text',
            field=models.BooleanField(blank=True, default=False, verbose_name='get texts'),
        ),
    ]
